version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: soundbot_postgres

    restart: always

    environment:
      POSTGRES_DB: soundbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: soundbot_redis

    restart: always

    ports:
      - "6379:6379"

  bot:
    build: .

    container_name: soundbot_bot

    restart: always

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
